### ISSUE TITLE
packages changes 3/2020

### ISSUE THREAD

**Issue by lyuouz-nysoag** [NYAG/dockers#70]
pyspark

**Comment by NYSAG-GS** [comment]
package: descartes
version: 1.1.0
reason: plotting shapefiles in matplotlib

**Comment by chansoosong** [comment]
spacy
reason: natural language processing
(https://pypi.org/project/spacy/)

tika 
reason: pdf extraction
(https://github.com/chrismattmann/tika-python)

**Comment by jasminemca-nyag** [comment]
in order to save static images created with plotly, you need orca.
here's how to get that working:

run the following in dumpling:
sudo npm install --unsafe-perm=true --allow-root -g electron@6.1.4 orca
sudo apt install xvfb
sudo mv /usr/bin/orca /usr/bin/orca-real
sudo nano /usr/bin/orca 

you should now have a text editor open. make it say this:
#!/bin/bash
xvfb-run -a /usr/bin/orca-real "$@"

then run this in dumpling:
sudo chmod 755 /usr/bin/orca

you should be good to go, if not try running this in your jupyter notebook:
plotly.io.orca.config.executable = '/usr/bin/orca'
plotly.io.orca.config.save()

**Comment by NYSAG-GS** [comment]
package: [contextily](https://github.com/darribas/contextily)
version: 0.99.0
reason: plotting base maps in matplotlib
This is what works for me to install
```sh
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install libgeos-dev -y
sudo apt-get install libproj-dev proj-data proj-bin -y
pip install contextily
```

**Comment by joe-graham-oag** [comment]
> 
> 
> pyspark

Is there a benefit to using this vs pandas? We're not currently utilizing a Spark cluster at this time to my knowledge.

**Comment by lyuouz-nysoag** [comment]
> > pyspark
> 
> Is there a benefit to using this vs pandas? We're not currently utilizing a Spark cluster at this time to my knowledge.

We have been getting very large datasets for opioids where Pandas simply doesn't work. Pandas loads the entire dataset into the memory before you can do any analysis, and a lot of these datasets just don't fit into the memory. PySpark instead does the so called lazy execution which will delay the operation until a result is needed in the pipeline, so that gives us the flexibility to work on the data without caching the entire thing in the memory.

**Comment by joe-graham-oag** [comment]
Mm, understandable. Thanks for the explanation, I wasn't aware of that part of PySpark. I'll go ahead and add it to the next build.

**Comment by jasminemca-nyag** [comment]
> package: descartes
> version: 1.1.0
> reason: plotting shapefiles in matplotlib

came here to ask for this!

**Comment by joe-graham-oag** [comment]
This is on my radar, I have the changes staged but ran into a separate issue testing to confirm the build worked. I'll try to get a build out by the end of the week.
