### ISSUE TITLE
Changing the quotes displayed on dumpling start

### ISSUE THREAD

**Issue by joe-graham-oag** [NYAG/dockers#73]
This issue is to track suggestions for new quotes to be added when dumpling is started.

**Comment by chansoosong** [comment]
"To Infinity and beyond" - Buzz
"Believe you can, then you will." - Mulan 

For more (scraped, parsed and cleaned from [some site](https://www.mulliganbrother.com/single-post/2017/09/26/50-Of-The-Best-Life-Quotes-From-Disney-Movies)): ` 
['"You control your destiny -- you don\'t need magic to do it. And   there are no magical shortcuts to solving your problems."  --  Merida',
 '"All it takes is faith and trust." --  Peter Pan',
 '"Listen with your heart, you will understand."  --  Grandmother Willow',
 '"Even miracles take a little time."  -- Fairy Godmother',
 '"If you focus on what you left behind, you will never be able to see what lies ahead."  --  Gusteau',
 '"The flower that blooms in adversity is the most rare and beautiful of all."  --  The Emperor',
 'Venture outside your comfort zone. The rewards are worth it."  -- Rapunzel',
 '"A true hero isn\'t measured by the size of his strength, but by the strength of his heart."  -- Zeus',
 '"Today is a good day to try."  -- Quasimodo',
 '"The very things that hold you down are going to lift you up."  - Timothy Mouse',
 '"Life\'s not a spectator sport. If watchin\' is all you\'re gonna do, then you\'re gonna watch your life go by without ya."  -- Laverne',
 '"Just because it\'s what\'s done, doesn\'t mean it\'s what should be done." -- Cinderella',
 '"The things that make me different are the things that make me."  -- Piglet',
 '"Don\'t just fly, soar."  -- Dumbo',
 '"If you don\'t know where you want to go, then it doesn\'t matter which path you take."  --  The Cheshire Cat',
 '"Believe you can, then you will."  -- Mulan',
 'I can go the distance. I will find my way if I can be strong. – Hercules',
 '"Admit defeat, and defeat will surely admit you into permanent custody."  -- Beret Girl',
 '"A little consideration, a little thought for others, makes all the difference."  --  Eeyore',
 '"Your identity is your most valuable possession. Protect it."  -- Elastigirl',
 '"Oh yes, the past can hurt. But the way I see it, you can either run from it or learn from it."  -- Rafiki',
 '"You\'re braver than you believe, and stronger than you seem, and smarter than you think." -- Winnie the Pooh',
 '"Everything that made that giant tree is already contained inside this tiny little seed. All it needs is some time, a little bit of sunshine and rain, and voilá! Now, y-you might not feel like you can do much now, but that\'s just because, well, you\'re not a tree yet. You just have to give yourself some time. You\'re still a seed."  - Flik',
 '"Our fate lives within us. You only have to be brave enough to see it." -- Merida',
 '"I\'m only brave when I have to be. Being brave doesn\'t mean you go looking for trouble."  -- Mufasa',
 '"Giving up is for rookies." -- Philoctetes',
 '"I don\'t want to survive. I want to live." (The Captain) wall-e',
 '"I give myself very good advice, but I very seldom follow it." -- Alice',
 '"Happiness is the richest thing we will ever own." -- Donald Duck',
 "What I really wanted was to prove that I could do things right, so that when I looked in the mirror, I'd see someone worthwhile. – Mulan",
 '"Sometimes the right path is not the easiest one." -- Grandmother Willow (Pocahontas)',
 '"Change is good." -- Rafiki',
 '"The only thing predictable about life is its unpredictability." -- Remy  o featuring many of these quotes. Video by -  RedFrost Motivation',
 '"Remember, you\'re the one who can fill the world with sunshine." --  Snow White',
 '"Do not be followed by its commonplace appearance. Like so many things, it is not what is outside, but what is inside that counts." -- Merchant (Aladdin)',
 '"Now, think of the happiest things. It\'s the same as having wings."  -- Peter Pan',
 '"The most important thing a girl wears is her confidence." – Cinderella',
 '"No matter how the wind howls, the mountain cannot bow to it." - The Emperor',
 '"If you can\'t say something nice, don\'t say nothing at all." - Thumper',
 '"For the strength of the Pack is the Wolf, and the strength of the Wolf is the Pack."  - Mowgli',
 '"Alwa ys let your conscience be your guide." -- The Blue Fairy',
 '."I never look back, darling! It distracts me from the now." - Edna Mode',
 'Or forgotten."  - Stitch',
 'But you\'ve got to make them happen, it all depends on you!" (Tiana to her mother) princess and the frog',
 '"If you don\'t think, then you shouldn\'t talk." -- March Hare',
 '."Just keep swimming" - Dory',
 "You want something done, you've got to do it yourself.  –Sebastian",
 'That destiny is not our own, but I know better. Our fate lives within us, you only have to be brave enough to see it." - Merida Inspiring and thought provoking video you may enjoy. Video by -    Brothers',
 '"If you can\'t learn to run with the pack, one of these days, you\'ll be someone\'s dinner." - Bagheera',
 'If watchin’ is all you’re gonna do, then you’re gonna watch your life go by without ya." - Gargoyle']
`

**Comment by jasminemca-nyag** [comment]
"The arc of the moral universe is long, but it bends toward justice." - MLK

**Comment by NYSAG-GS** [comment]
"History, despite its wrenching pain cannot be unlived, but if faced with courage need not be lived again." - Maya Angelou

"Gradually I learned to be indifferent to myself and my deficiencies; I came to centre my attention increasingly upon external objects: the state of the world, various branches of knowledge, individuals for whom I felt affection." - Bertrand Russell

"Luck affects everything. Let your hook always be cast; in the stream where you least expect it there will be a fish." - Ovid
